### ISSUE TITLE
bug: the balls pass through the bricks

### ISSUE THREAD

**Issue by SinaKarimi7** [JalalHamed/click-brick-breaker#1]
Hello,
It is a very interesting game that I enjoyed playing. But sometimes there are problems in the ball flow and the balls pass through the bricks. Also, that specific brick counter does not decrease.

I just want to report this bug here so I don't expect you to fix it.

![image](https://github.com/JalalHamed/click-brick-breaker/assets/16350906/8abc4091-aa45-42bd-8137-c8ed1fdf4d5e)

**Comment by SinaKarimi7** [comment]
Haha, now I see you mentioned this in `README.md`. 
> still projectiles find a way through inside of the bricks!

Well, feel free to close this issue :))

**Comment by JalalHamed** [comment]
:) Appreciate you taking the time
